#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : zsys.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Oct 01 20:13:01 -0400 2018
# SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: zsys.sh [-help]
# usage: zsys.sh [-lib_map_path]
# usage: zsys.sh [-noclean_files]
# usage: zsys.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'zsys.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_lib axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_3 axi_vip_v1_1_3 processing_system7_vip_v1_0_5 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 lib_pkg_v1_0_2 fifo_generator_v13_2_2 lib_fifo_v1_0_11 blk_mem_gen_v8_4_1 lib_bmg_v1_0_10 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_19 axi_vdma_v6_3_5 axis_infrastructure_v1_1_0 axis_data_fifo_v1_1_18 axi_lite_ipif_v3_0_4 v_tc_v6_1_12 v_vid_in_axi4s_v4_0_8 v_axi4s_vid_out_v4_0_9 xlconcat_v2_1_1 xlslice_v1_0_1 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_17 axi_data_fifo_v2_1_16 axi_crossbar_v2_1_18 axi_protocol_converter_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "zsys.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lib $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec17/hdl/axi_reg32_v1_0_S_AXI.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec17/hdl/axi_reg32_v1_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_reg32_0_0/sim/zsys_axi_reg32_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_processing_system7_0_0/sim/zsys_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_rst_processing_system7_0_50M_0/sim/zsys_rst_processing_system7_0_50M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/9340/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_19 $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec8a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_5 $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_vdma_0_0/sim/zsys_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v1_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5738/hdl/axis_data_fifo_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axis_data_fifo_0_0/sim/zsys_axis_data_fifo_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5143/hdl/dualport_ram.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5143/hdl/gamma_rom.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5143/hdl/axis_raw_demosaic_v1_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axis_raw_demosaic_0_0/sim/zsys_axis_raw_demosaic_0_0.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/c887/hdl/axis_raw_unpack_v1_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axis_raw_unpack_0_0/sim/zsys_axis_raw_unpack_0_0.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/f76f/hdl/axis_video_resize_v1_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axis_video_resize_0_0/sim/zsys_axis_video_resize_0_0.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/94dd/hdl/phy_clock_system.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/94dd/hdl/line_if.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/94dd/hdl/csi2_d_phy_rx.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_csi2_d_phy_rx_0_0/sim/zsys_csi2_d_phy_rx_0_0.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/2dbd/hdl/csi2_parser.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/2dbd/hdl/lane_align.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/2dbd/hdl/lane_merge.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/2dbd/hdl/csi_to_axis_v1_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_csi_to_axis_0_0/sim/zsys_csi_to_axis_0_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_proc_sys_reset_0_0/sim/zsys_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/a47b/hdl/tmds_encoder.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/a47b/hdl/serdes.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/a47b/hdl/dvi_encoder.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/a47b/hdl/clock_system.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/a47b/hdl/Video_IO_2_HDMI_TMDS_v1_0.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/a47b/hdl/dram16xn.vhd" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/a47b/hdl/convert_30to15_fifo.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_Video_IO_2_HDMI_TMDS_0_0/sim/zsys_Video_IO_2_HDMI_TMDS_0_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_vdma_0_1/sim/zsys_axi_vdma_0_1.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/83c4/src/axis_fb_conv_v1_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axis_fb_conv_0_0/sim/zsys_axis_fb_conv_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/zsys_clk_wiz_1_0_mmcm_pll_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/proc_common_v3_00_a/hdl/src/vhdl/zsys_clk_wiz_1_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/proc_common_v3_00_a/hdl/src/vhdl/zsys_clk_wiz_1_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/proc_common_v3_00_a/hdl/src/vhdl/zsys_clk_wiz_1_0_ipif_pkg.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/proc_common_v3_00_a/hdl/src/vhdl/zsys_clk_wiz_1_0_family_support.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/proc_common_v3_00_a/hdl/src/vhdl/zsys_clk_wiz_1_0_family.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/proc_common_v3_00_a/hdl/src/vhdl/zsys_clk_wiz_1_0_soft_reset.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/proc_common_v3_00_a/hdl/src/vhdl/zsys_clk_wiz_1_0_pselect_f.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/zsys_clk_wiz_1_0_address_decoder.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/zsys_clk_wiz_1_0_slave_attachment.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/zsys_clk_wiz_1_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/zsys_clk_wiz_1_0_clk_wiz_drp.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/zsys_clk_wiz_1_0_axi_clk_config.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/zsys_clk_wiz_1_0_clk_wiz.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_wiz_1_0/zsys_clk_wiz_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_12 $vhdlan_opts \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/6694/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/d987/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/9a07/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_v_axi4s_vid_out_0_0/sim/zsys_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_v_tc_0_0/sim/zsys_v_tc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlconcat_0_0/sim/zsys_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/f3db/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlslice_0_0/sim/zsys_xlslice_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xbar_0/sim/zsys_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/sim/zsys.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../zb-cam-1.srcs/sources_1/bd/zsys/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_auto_pc_6/sim/zsys_auto_pc_6.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_auto_pc_5/sim/zsys_auto_pc_5.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_auto_pc_4/sim/zsys_auto_pc_4.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_auto_pc_3/sim/zsys_auto_pc_3.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_auto_pc_2/sim/zsys_auto_pc_2.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_auto_pc_7/sim/zsys_auto_pc_7.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_auto_pc_1/sim/zsys_auto_pc_1.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_auto_pc_0/sim/zsys_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.zsys xil_defaultlib.glbl -o zsys_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./zsys_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./zsys.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key zsys_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc zsys_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./zsys.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: zsys.sh [-help]\n\
Usage: zsys.sh [-lib_map_path]\n\
Usage: zsys.sh [-reset_run]\n\
Usage: zsys.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
