# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z045ffv900-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/ip_repo/edit_vbacc_v1_0.cache/wt [current_project]
set_property parent.project_path C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/ip_repo/edit_vbacc_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/ip_repo/vbacc_1.0
  c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/IP_LIB
} [current_project]
set_property ip_output_repo c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/ip_repo/edit_vbacc_v1_0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/ip_repo/vbacc_1.0/hdl/vbacc_v1_0_M00_AXIS_VIDEO.vhd
  C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/ip_repo/vbacc_1.0/hdl/vbacc_v1_0_M00_AXI_STATUS.vhd
  C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/ip_repo/vbacc_1.0/hdl/vbacc_v1_0_S00_AXIS_VIDEO.vhd
  C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/ip_repo/vbacc_1.0/hdl/vbacc_v1_0_S00_AXI_CFG.vhd
  C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/ip_repo/vbacc_1.0/hdl/vbacc_v1_0.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top vbacc_v1_0 -part xc7z045ffv900-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vbacc_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vbacc_v1_0_utilization_synth.rpt -pb vbacc_v1_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
