# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.cache/wt [current_project]
set_property parent.project_path C:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths C:/Users/John/Documents/ZynqBerry/te0726_m_demo1/board_files [current_project]
set_property board_part trenz.biz:te0726_m:part0:3.1 [current_project]
set_property ip_repo_paths c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.ipdefs/ip_lib_0 [current_project]
set_property ip_output_repo c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/hdl/zsys_wrapper.vhd
add_files C:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/zsys.bd
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_processing_system7_0_0/zsys_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_rst_processing_system7_0_50M_0/zsys_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_rst_processing_system7_0_50M_0/zsys_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_rst_processing_system7_0_50M_0/zsys_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_axi_vdma_0_0/zsys_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_axi_vdma_0_0/zsys_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_axi_vdma_0_0/zsys_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_csi2_d_phy_rx_0_0/hdl/csi2_d_phy_rx.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_csi_to_axis_0_0/hdl/csi_to_axis.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_0_0/zsys_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_0_0/zsys_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_0_0/zsys_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_axi_vdma_0_1/zsys_axi_vdma_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_axi_vdma_0_1/zsys_axi_vdma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_axi_vdma_0_1/zsys_axi_vdma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_1_0/zsys_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_1_0/zsys_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_1_0/zsys_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_v_axi4s_vid_out_0_0/zsys_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_v_axi4s_vid_out_0_0/zsys_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_v_tc_0_0/zsys_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_v_tc_0_0/zsys_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_xbar_0/zsys_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_0/zsys_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_auto_us_0/zsys_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_auto_us_0/zsys_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_1/zsys_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_2/zsys_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/zsys_ooc.xdc]
set_property is_locked true [get_files C:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/sources_1/bd/zsys/zsys.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/constrs_1/imports/constraints/vivado_target.xdc
set_property used_in_implementation false [get_files C:/Users/John/Documents/ZynqBerry/LVS_BASE/LVS_BASE.srcs/constrs_1/imports/constraints/vivado_target.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top zsys_wrapper -part xc7z010clg225-1


write_checkpoint -force -noxdef zsys_wrapper.dcp

catch { report_utilization -file zsys_wrapper_utilization_synth.rpt -pb zsys_wrapper_utilization_synth.pb }
