# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.cache/wt [current_project]
set_property parent.project_path C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part trenz.biz:te0726_m:part0:3.1 [current_project]
set_property ip_repo_paths c:/Users/DEV/Documents/ZynqBerry/LVS_BASE/LVS_BASE.ipdefs/ip_lib_0 [current_project]
set_property ip_output_repo c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/hdl/zsys_wrapper.vhd
add_files C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/zsys.bd
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_processing_system7_0_0/zsys_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_rst_processing_system7_0_50M_0/zsys_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_rst_processing_system7_0_50M_0/zsys_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_rst_processing_system7_0_50M_0/zsys_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_axi_vdma_0_0/zsys_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_axi_vdma_0_0/zsys_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_axi_vdma_0_0/zsys_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_csi2_d_phy_rx_0_0/hdl/csi2_d_phy_rx.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_csi_to_axis_0_0/hdl/csi_to_axis.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_0_0/zsys_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_0_0/zsys_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_0_0/zsys_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_axi_vdma_0_1/zsys_axi_vdma_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_axi_vdma_0_1/zsys_axi_vdma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_axi_vdma_0_1/zsys_axi_vdma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_1_0/zsys_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_1_0/zsys_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_clk_wiz_1_0/zsys_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_v_axi4s_vid_out_0_0/zsys_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_v_axi4s_vid_out_0_0/zsys_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_v_tc_0_0/zsys_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_v_tc_0_0/zsys_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_xbar_0/zsys_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_6/zsys_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_5/zsys_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_4/zsys_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_3/zsys_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_2/zsys_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_7/zsys_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_1/zsys_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_0/zsys_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/sources_1/bd/zsys/zsys_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/constrs_1/imports/constraints/vivado_target.xdc
set_property used_in_implementation false [get_files C:/Users/DEV/Documents/GitHub/OSSDC_SmartCamGen1/HW/ZynqBerry/zb-cam-1/zb-cam-1.srcs/constrs_1/imports/constraints/vivado_target.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top zsys_wrapper -part xc7z010clg225-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zsys_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zsys_wrapper_utilization_synth.rpt -pb zsys_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
